// 用以记录相关的action常量
export const LOADING_STATUS_CHANGE = 'LOADING_STATUS_CHANGE';
export const LOADING_STATUS_ACTION = 'LOADING_STATUS_ACTION';

export const CONTENT_NAVBAR = 'CONTENT_NAVBAR';
export const CONTENT_NAVBAR_ACTION = 'CONTENT_NAVBAR_ACTION';

export const CONTENT_NAVBAR_CHANGE = 'CONTENT_NAVBAR_CHANGE';
export const CONTENT_NAVBAR_CHANGE_ACTION = 'CONTENT_NAVBAR_CHANGE_ACTION';

export const CONTENT_ITEMS_UPDATE = 'CONTENT_ITEMS_UPDATE';
export const CONTENT_ITEMS_UPDATE_ACTION = 'CONTENT_NAVBAR_ACTION';

export const CONTENT_TAB_CHANGE = 'CONTENT_TAB_CHANGE';
export const CONTENT_TAB_CHANGE_ACTION = 'CONTENT_TAB_CHANGE_ACTION';

export const CONTENT_FRIEND = 'CONTENT_FRIEND';
export const CONTENT_FRIEND_ACTION = 'CONTENT_FRIEND_ACTION';