export const LOADING_STATUS_CHANGE = 'LOADING_STATUS_CHANGE';
export const LOADING_STATUS_ACTION = 'LOADING_STATUS_ACTION';

export const CONTENT_NAVBAR = 'CONTENT_NAVBAR';
export const CONTENT_NAVBAR_ACTION = 'CONTENT_NAVBAR_ACTION';